
""" wiki category to KDD """

WikiToKDD = {
"Computer hardware":"Computers\Hardware",
"Internet":"Computers\Internet & Intranet",
"Computer networks":"Computers\Internet & Intranet",
"Mobile computers":"Computers\Mobile Computing",
"Multimedia":"Computers\Multimedia",
"Networks":"Computers\Networks & Telecommunication",
"Telecommunications":"Computers\Networks & Telecommunication",
"Computer security":"Computer security",
"Software":"Computers\Software",
"Computing":"Computers\Other",
"Celebrity":"Entertainment\Celebrities",
"Games":"Entertainment\Games & Toys",
"Toys":"Entertainment\Games & Toys",
"Humour":"Entertainment\Humor & Fun",
"Film":"Entertainment\Movies",
"Music":"Entertainment\Music",
"Photographs":"Entertainment\Pictures & Photos",
"Radio":"Entertainment\Radio",
"Television":"Entertainment\TV",
"Entertainment":"Entertainment\Other",
"Arts":"Information\Arts & Humanities",
"Humanities":"Information\Arts & Humanities",
"Companies":"Information\Companies & Industries",
"Industries":"Information\Companies & Industries",
"Science":"Information\Science & Technology",
"Technology":"Information\Science & Technology",
"Education":"Information\Education",
"Law":"Information\Law & Politics",
"Politics":"Information\Law & Politics",
"Regions":"Information\Local & Regional",
"Municipalities":"Information\Local & Regional",
"Local government":"Information\Local & Regional",
"Reference":"Information\References & Libraries",
"Libraries":"Information\References & Libraries",
"Information":"Information\Other",
"Books":"Living\Book & Magazine",
"Magazines":"Living\Book & Magazine",
"Automobiles":"Living\Car & Garage",
"Garages (residential)":"Living\Car & Garage",
"Garages (parking)":"Living\Car & Garage",
"Employment":"Living\Career & Jobs",
"Dating":"Living\Dating & Relationships",
"Intimate relationships":"Living\Dating & Relationships",
"Family":"Living\Family & Kids",
"Children":"Living\Family & Kids",
"Fashion":"Living\Fashion & Apparel",
"Clothing":"Living\Fashion & Apparel",
"Finance":"Living\Finance & Investment",
"Investment":"Living\Finance & Investment",
"Food and drink":"Living\Food & Cooking",
"Cooking":"Living\Food & Cooking",
"Decorative arts":"Living\Furnishing & Houseware",
"Furnishings":"Living\Furnishing & Houseware",
"Home appliances":"Living\Furnishing & Houseware",
"Giving":"Living\Gifts & Collectables",
"Collecting":"Living\Gifts & Collectables",
"Health":"Living\Health & Fitness",
"Physical exercise":"Living\Health & Fitness",
"Landscape":"Living\Landscaping & Gardening",
"Horticulture and gardening":"Living\Landscaping & Gardening",
"Pets":"Living\Pets & Animals",
"Animals":"Living\Pets & Animals",
"Real estate":"Living\Real Estate",
"Religion":"Living\Religion & Belief",
"Belief":"Living\Religion & Belief",
"Tools":"Living\Tools & Hardware",
"Hardware (mechanical)":"Living\Tools & Hardware",
"Travel":"Living\Travel & Vacation",
"Holidays":"Living\Travel & Vacation",
"Personal life":"Living\Other",
"Online chat":"Online Community\Chat & Instant Messaging",
"Instant messaging":"Online Community\Chat & Instant Messaging",
"Internet forums":"Online Community\Forums & Groups",
"Websites":"Online Community\Homepages",
"Internet celebrities":"Online Community\People Search",
"Social networking services":"Online Community\Personal Services",
"Virtual communities":"Online Community\Other",
"Internet culture":"Online Community\Other",
"Auctioneering":"Shopping\Auctions & Bids",
"Retailing":"Shopping\Stores & Products",
"Product management":"Shopping\Stores & Products",
"Consumer behaviour":"Shopping\Buying Guides & Researching",
"Consumer protection":"Shopping\Buying Guides & Researching",
"Renting":"Shopping\Lease & Rent",
"Sales promotion":"Shopping\Bargains & Discounts",
"Bargaining theory":"Shopping\Bargains & Discounts",
"Distribution, retailing, and wholesaling":"Shopping\Other",
"American football":"Sports\American Football",
"Auto racing":"Sports\Auto Racing",
"Baseball":"Sports\Baseball",
"Basketball":"Sports\Basketball",
"Hockey":"Sports\Hockey",
"Works about sports":"Sports\News & Scores",
"Sports events":"Sports\Schedules & Tickets",
"Sports seasons":"Sports\Schedules & Tickets",
"Association football":"Sports\Soccer",
"Tennis":"Sports\Tennis",
"Olympic Games":"Sports\Olympic Games",
"Outdoor recreation":"Sports\Outdoor Recreations",
"Sports":"Sports\Other"
}






if __name__ == "__main__":
	print "hi"


